spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/springpostgre
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: product-service
  cloud:
    config:
      uri: http://localhost:8080
      username: root
      password: s3cr3t
  boot:
    admin:
      client:
        url: http://localhost:8086
