#Application Configuration
server:
  port: 8095
  error:
    include-message: always
    include-binding-errors: always
app:
  jwt:
    expiration-ms: 86400000

jwt:
  token:
    validity: 18000
    prefix: Bearer
  signing:
    key: ${SECURITY_KEY_0001:signingkey}
  authorities:
    key: roles
  header:
    string: Authorization
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME}:5432/springpostgre
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  boot:
    admin:
      client:
        enabled: true
        url: http://${HOSTNAME_ADMIN}:${PORT_ADMIN:8086}
        username: ${USERNAME_ADMIN:root}
        password: ${SECRET_ADMIN:s3cr3tAdmin}
        instance:
          prefer-ip: true
          metadata:
            tags:
              environment: development
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
eureka:
  client:
    healthcheck:
      enabled: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${USERNAME_EUREKA:root}:${SECRET_EUREKA:s3cr3tEureka}@${HOSTNAME_EUREKA}:8099/eureka/
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
    metadata-map:
      user.name: client
      user.password: client
