#Application Configuration
server:
  port: 8095
  error:
    include-message: always
    include-binding-errors: always
app:
  jwt:
    expiration-ms: 86400000

jwt:
  token:
    validity: 18000
    prefix: Bearer
  signing:
    key: ${SECURITY_KEY_0001:signingkey}
  authorities:
    key: roles
  header:
    string: Authorization
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME}:5432/springpostgre
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://${USERNAME_EUREKA:root}:${SECRET_EUREKA:s3cr3tEureka}@${HOSTNAME_EUREKA}:8099/eureka/
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
