#Application Configuration
server:
  port: 8093
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
spring:
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME}:5432/springpostgre
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  boot:
    admin:
      client:
        enabled: true
        url: http://${HOSTNAME_ADMIN}:${PORT_ADMIN:8086}
        username: ${USERNAME_ADMIN:root}
        password: ${SECRET_ADMIN:s3cr3tAdmin}
        instance:
          prefer-ip: true
          metadata:
            tags:
              environment: development
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    healthcheck:
      enabled: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${USERNAME_EUREKA:root}:${SECRET_EUREKA:s3cr3tEureka}@${HOSTNAME_EUREKA}:8099/eureka/
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
    metadata-map:
      user.name: client
      user.password: client

Feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"