# CONFIG SERVICE
apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-service
  name: config-service
  namespace: default
spec:
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
# CONFIG DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: config-service
  name: config-service
  namespace: default
spec:
  replicas: 1 #CHANGE
  revisionHistoryLimit: 5
  minReadySeconds: 120
  selector:
    matchLabels:
      app: config-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: config-image:1.0
          ports:
            - containerPort: 8081
          env:
            - name: USERNAME_CONFIG
              value: "root"
            - name: SECRET_CONFIG
              value: "s3cr3t"
            - name: GIT_USER
              value: "dEfter@2313"
            - name: GIT_PASSWORD
              value: "adrianherrera.r.e@gmail.com"

