---
# DISCOVER SERVICE
apiVersion: v1
kind: Service
metadata:
  labels:
    app: discover-service
  name: discover-service
  namespace: default
spec:
  ports:
    - #nodePort: 32393
      port: 8099 #puerto expuesto
      protocol: TCP
      targetPort: docker-port #puerto interno
      nodePort: 30399
  selector:
    app: discover-service
  #sessionAffinity: si es None no mantiene la sesion, si es ClientIP mantiene la sesion para el usuario con la ip
  sessionAffinity: None
  type: NodePort

---
# DISCOVER DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: discover-service
  name: discover-service
  namespace: default
spec:
  replicas: 1 #CHANGE
  revisionHistoryLimit: 5
  minReadySeconds: 120
  selector:
    matchLabels:
      app: discover-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: discover-service
    spec:
      containers:
        - name: discover-service
          image: discover-image:1.0
          ports:
            - name: docker-port
              containerPort: 8099
          resources: #ASIGNACION DE RECURSOS
            limits:
              cpu: 600m
              memory: 600Mi #MAX
          env:
            - name: HOSTNAME_CONFIG
              value: "config-service"
            - name: PORT_CONFIG
              value: "8081"
            - name: USERNAME_CONFIG
              value: "root"
            - name: SECRET_CONFIG
              value: "s3cr3t"
            - name: HOSTNAME_EUREKA
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: USERNAME_EUREKA
              value: "root"
            - name: SECRET_EUREKA
              value: "s3cr3tEureka"
