apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-service
  name: gateway-service
  namespace: default
spec:
  ports:
    - #nodePort: 32393
      port: 8080 #puerto expuesto
      protocol: TCP
      targetPort: docker-port #puerto interno
      nodePort: 30380
  selector:
    app: gateway-service
  #sessionAffinity: si es None no mantiene la sesion, si es ClientIP mantiene la sesion para el usuario con la ip
  sessionAffinity: None
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway-service
  name: gateway-service
  namespace: default
spec:
  replicas: 1 #CHANGE
  revisionHistoryLimit: 5
  minReadySeconds: 120
  selector:
    matchLabels:
      app: gateway-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: gateway-image:1.0
          ports:
            - name: docker-port
              containerPort: 8080
          resources: #ASIGNACION DE RECURSOS
            limits:
              cpu: 600m
              memory: 600Mi #MAX
          env:
            - name: HOSTNAME_CONFIG
              value: "config-service"
            - name: PORT_CONFIG
              value: "8081"
            - name: USERNAME_CONFIG
              value: "root"
            - name: SECRET_CONFIG
              value: "s3cr3t"
            - name: HOSTNAME_EUREKA
              value: "discover-service"
            - name: USERNAME_EUREKA
              value: "root"
            - name: SECRET_EUREKA
              value: "s3cr3tEureka"
            - name: HOSTNAME_ADMIN
              value: "admin-service"
            - name: PORT_ADMIN
              value: "8086"
            - name: USERNAME_ADMIN
              value: "root"
            - name: SECRET_ADMIN
              value: "s3cr3tAdmin"
